[build]
    command = "cd DonjonMonstres && npx ts-node build.ts"
    functions = "functions"
[functions]
    external_node_modules = ["express"]
    node_bundler = "esbuild"
[[redirects]]
    force = true
    from = "/*"
    status = 200
    to = "/.netlify/functions/api/:splat"
